Miguel class sprint
Digital-Dreamers/fly_away_client pull request #7
Opened 2022-04-23 19:04 UTC by MgARL

Created Context and Results page

2022-04-23 19:24 UTC, OttoSJ approved these changes

2022-04-23 19:28 UTC, NaheedAwan requested changes
Your route path does'nt matches the nav link path in nav bar thats why it can't be functional

2022-04-23 23:23 UTC, MgARL commented
> nav

Where is that at?

2022-04-23 23:33 UTC, NaheedAwan requested changes
<Route path='/reservation/:id' element={<Reservation />
  <Nav.Link as={Link} to="/reservations">Reservations</Nav.Link>
they are different so not working when i checked it

2022-04-24 00:12 UTC, NaheedAwan approved these changes

2022-04-24 00:18 UTC, merged